
development:
  adapter: postgresql
  encoding: unicode
  database: appi-dev
  pool: 5
  host: localhost
  username: resonante
  password: 
 
test:
  adapter: postgresql
  encoding: unicode
  database: appi-test
  pool: 5
  host: localhost
  username: resonante
  password: 
 
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: der1a3nhv8g39t
  username: bhdrlcymgslcxe
  password: TYv_0Cc3IFZEU6LGCSXp41XXPD
  host: ec2-54-228-227-217.eu-west-1.compute.amazonaws.com
  port: 5432