# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69e26621fe9c9759a370c8cf63f075b2a7517f79b3c5a237e25608a885c3b1019d3b06ccfb60fda2fb33854d94d3ccab1c0c1c95b77392cfc4c610461603d984

test:
  secret_key_base: 5a6d0733fe02947b7cb86e1e98184bca051a755799efbad361f3db260087143c05bacfd1af3bb50bbcb4c7d80510c13c5186baea3acb0b7b8f3f05a2bf47c435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
